# Generated by Django 4.1.3 on 2022-12-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='lname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='members121',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='members121',
            old_name='lname',
            new_name='lastname',
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='members121',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
